name: osaka
description: Blog-aware static code generator for Jekyll-style Markdown posts in Flutter.
version: 0.0.2
homepage: https://github.com/mehmetoguzderin/osaka

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.2.2
  dart_style: ^1.3.3
  glob: ^1.2.0
  path: ^1.6.4
  yaml: ^2.2.0